### ISSUE TITLE
blog hero bug

### ISSUE THREAD

**Issue by naps62** [subvisual/subvisual.com#539]
![image](https://github.com/subvisual/subvisual.com/assets/283819/3b52c3b4-7edc-42ea-a0de-2acabb98d620)

**Comment by mirhamasala** [comment]
@naps62 Is this still happening? If so, is this on Chrome?

**Comment by mirhamasala** [comment]
@gabrielpoca I remember reading something about trying to optimize the images? Is it related to what @naps62 is mentioning about the image being heavily pixelated?

**Comment by gabrielpoca** [comment]
@mirhamasala I think those images are already pixelated to begin with. I check the original in PNG and it looks the same to my eyes.

**Comment by gabrielpoca** [comment]
I think this is on purpose, is it not?

**Comment by naps62** [comment]
if it's on purpose, I have to say it was a terrible idea
in a large enough screen (I was more or less in 1080p res), it looks like 💩

**Comment by gabrielpoca** [comment]
I asked on Slack.

**Comment by naps62** [comment]
This appears solved
