### ISSUE TITLE
iPand Mini 1st gen iOS 6 Safari bugs

### ISSUE THREAD

**Issue by vis-kid** [subvisual/subvisual.com#97]
Hi! Found a couple of bugs on my mini. Took landscape and portrait screenshots where necessary. 

They show a couple of bugs that are mostly self-explanatory I guess. But feel free to get back in touch with me if you have any questions or need more screenshots. Happy to help!  

Whitespace issues seem to be most prominent. 

 The menu is all over the place in some cases and the hamburger icon is missing too.

/community took the hardest hit, basically a blank page with “endless” scroll.

/blog seems alright

Animated ballon on /apprenticeship works fine. No clouds though.

Hope this was helpful :)

![photo 5](https://cloud.githubusercontent.com/assets/1353214/8799750/c7a5f4d0-2fac-11e5-8aae-ee97f6e9c814.PNG)
![image 2](https://cloud.githubusercontent.com/assets/1353214/8799598/9af277f2-2fab-11e5-8132-5a01c2e4ad4b.png)
![image 3](https://cloud.githubusercontent.com/assets/1353214/8799599/9af3ac62-2fab-11e5-86d2-625022520f79.png)
![image 4](https://cloud.githubusercontent.com/assets/1353214/8799602/9af737ec-2fab-11e5-914b-3592741a6fb4.png)
![image 5](https://cloud.githubusercontent.com/assets/1353214/8799601/9af4ffd6-2fab-11e5-9aaf-d8404608291b.png)
![image 6](https://cloud.githubusercontent.com/assets/1353214/8799600/9af4af2c-2fab-11e5-8dff-5e738ef32769.png)
![image](https://cloud.githubusercontent.com/assets/1353214/8799603/9af9450a-2fab-11e5-82ce-ac46e985aad6.png)
![image 2](https://cloud.githubusercontent.com/assets/1353214/8799606/9b0c634c-2fab-11e5-8f23-5e2009de708e.png)
![image 3](https://cloud.githubusercontent.com/assets/1353214/8799604/9b0ac62c-2fab-11e5-8d3b-70c7b6dc37bc.png)
![image 4](https://cloud.githubusercontent.com/assets/1353214/8799605/9b0acf3c-2fab-11e5-8b49-c73fb67e46ac.png)
![image 5](https://cloud.githubusercontent.com/assets/1353214/8799609/9b12d2fe-2fab-11e5-9936-fc738e84ba29.png)
![image](https://cloud.githubusercontent.com/assets/1353214/8799607/9b0f4f4e-2fab-11e5-81e7-e606401cc8fd.png)
![image 2](https://cloud.githubusercontent.com/assets/1353214/8799611/9b24732e-2fab-11e5-8efc-cbdb52bda721.png)
![image 3](https://cloud.githubusercontent.com/assets/1353214/8799610/9b2099c0-2fab-11e5-8849-5e3902a2f2d1.png)
![image 4](https://cloud.githubusercontent.com/assets/1353214/8799617/9b3af9e6-2fab-11e5-9e93-00a7f8a867e7.png)
![image 5](https://cloud.githubusercontent.com/assets/1353214/8799613/9b2813a8-2fab-11e5-9826-5e47bb3dc78e.png)
![image](https://cloud.githubusercontent.com/assets/1353214/8799614/9b28a94e-2fab-11e5-8c24-51d7585bf6d6.png)
![image 2](https://cloud.githubusercontent.com/assets/1353214/8799615/9b2e9dfe-2fab-11e5-87dd-0e14b15f53b8.png)
![image 3](https://cloud.githubusercontent.com/assets/1353214/8799616/9b3a5af4-2fab-11e5-80cb-d98b04b70fd7.png)
![image 4](https://cloud.githubusercontent.com/assets/1353214/8799612/9b26b85a-2fab-11e5-818e-aefa3e7921b2.png)
![image 5](https://cloud.githubusercontent.com/assets/1353214/8799618/9b41e04e-2fab-11e5-9b23-0073046a0264.png)
![image](https://cloud.githubusercontent.com/assets/1353214/8799619/9b471028-2fab-11e5-8863-d7229346e2ef.png)

**Comment by naps62** [comment]
Thanks @vis-kid 
It seems some of these issues only occur in iOS or Android, and are not reproducible by resizing the browser window, which made them go unnoticed.
But we'll be looking into these during the next few days

**Comment by vis-kid** [comment]
Sure, anytime! :)

That makes sense, thought the same.

A device lab sure would be handy in such cases ;)

**Comment by joaojusto** [comment]
Closing
